server:
  port: 8003

spring:
  application:
    name: location-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/CargoTrackingSystem?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: '023455'

mybatis:
  type-aliases-package: com.nju.springcloud.entities
  # To avoid class with the same name